FROM debian:latest
ADD startInstances.sh /tmp
ADD patchInstall.sh /tmp
ADD dummyRespond.txt /tmp

COPY ./fog_1.5.0 /tmp/fog_1.5.0

RUN cd /tmp \
 && cd fog_1.5.0/bin \
 && cat /tmp/dummyRespond.txt | bash ./installfog.sh 
# && bash ./installfog.sh 
 
EXPOSE 21/tcp 80/tcp 111/tcp 2049/tcp 4045/tcp 8099/tcp 9098/tcp 34463/tcp 69/udp 111/udp 212/udp 2049/udp 4045/udp 34463/udp

CMD ["/tmp/startInstances.sh"]