FROM debian:latest
ADD startInstances.sh /tmp

EXPOSE 21/tcp 80/tcp 111/tcp 2049/tcp 4045/tcp 8099/tcp 9098/tcp 34463/tcp 69/udp 111/udp 212/udp 2049/udp 4045/udp 34463/udp

CMD ["/tmp/startInstances.sh"]