FROM debian:latest
MAINTAINER Felix Friedberger <felix.friedberger@rwth-aachen.de>

##DOWNLOAD ALL PACKAGES
RUN apt-get update
RUN apt-get install -y iproute2 locales wget net-tools nano git
##RUN apt-get install -y python2.7 python-pip
RUN apt-get install -y bc cpp curl g++ gawk gcc gzip htmldoc isolinux m4 unzip xinetd zlib1g
RUN apt-get install -y apache2 build-essential genisoimage lftp libapache2-mod-php7.0 liblzma-dev mysql-client mysql-server nfs-kernel-server openssh-server php-gettext php7.0 php7.0-bcmath php7.0-curl php7.0-fpm php7.0-gd php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysqlnd sysv-rc-conf tar tftp-hpa tftpd-hpa vsftpd 
RUN apt-get -y install python
RUN apt-get clean 
RUN locale-gen en_US.UTF-8
