FROM ubuntu:latest
MAINTAINER Felix Friedberger <felix.friedberger@rwth-aachen.de>

##DOWNLOAD ALL PACKAGES
RUN apt-get update
RUN apt-get install -y iproute2 locales wget net-tools nano git
RUN apt-get install -y python2.7 python-pip
RUN apt-get clean 
RUN locale-gen en_US.UTF-8
